# Generated by Django 2.2.6 on 2019-11-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('usr_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('usr_pwd', models.CharField(max_length=45)),
                ('usr_name', models.CharField(max_length=45)),
                ('usr_email', models.CharField(max_length=45)),
                ('usr_phone', models.CharField(max_length=45)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
