# Generated by Django 2.2.6 on 2019-11-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usr_name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
