# Generated by Django 2.2.6 on 2019-11-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['-reg_date']},
        ),
    ]
