# Generated by Django 2.2.6 on 2019-11-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_idx', models.IntegerField(primary_key=True, serialize=False)),
                ('item_category', models.IntegerField(default=1)),
                ('item_name', models.CharField(max_length=45)),
                ('item_content', models.TextField()),
                ('item_price', models.IntegerField()),
                ('on_sale', models.BooleanField(default=True)),
                ('read_count', models.IntegerField(default=0)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
