# Generated by Django 2.2.7 on 2019-11-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
