# Generated by Django 2.2.7 on 2019-12-10 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_idx', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=45)),
                ('product_img', models.ImageField(blank=True, upload_to='')),
                ('prouct_like', models.IntegerField(default=0)),
                ('usr_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
