# Generated by Django 2.2.7 on 2019-12-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_profile',
            field=models.ImageField(default=0, upload_to='event/profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, upload_to='event/%Y/%m/%d'),
        ),
    ]
